### ISSUE TITLE
The dataset uploaded in huggingface seems not to have segmentation labels.

### ISSUE THREAD

**Issue by Roberyan** [zhu-xlab/rrsis#1]
As title, can you tell me where the segmentation labels are? Or am I finding the wrong direction or usage?

**Comment by Roberyan** [comment]
well, I see the segmentation is mixed with original images in the dataset, but the problem is where is your referring text? Could please provide it?

**Comment by YZHJessica** [comment]
Sorry, I accidentally deleted the comment.
It looks like this issue was addressed in an email to you a month ago.
Please kindly download the RefSegRS.zip. 
This zip file definitely includes the segmentation labels and text :)
